[project]
name = "binsketch-algorithm"
version = "0.1.0"
description = "Reproduce binsketch"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "gdown",
    "tqdm",
    "ipykernel",
    "matplotlib",
]
